title: "Sab0x1D::Threat Intel"
description: "Cybersecurity awareness series and threat intelligence by Sab0x1D"
url: "https://x1dlabs.com
baseurl: ""
future: true
timezone: "Australia/Adelaide"

# Theme + Markdown
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Collections
collections:
  listings:
    output: true
    permalink: /listings/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "listings"
    values:
      layout: "listing"
      author: "Sab0x1D"
      author_avatar: "/assets/img/sab01xd-profile.jpeg"
      featured: false
      published: true

# Exclude and include paths
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github/
  - _site/
  - .vscode/
  - .DS_Store

# Feed
feed:
  path: feed.xml

# SEO + Social
social_links:
  github: sab0x1d
  twitter: sab0x1d

# Pagination (if used)
paginate: 6
paginate_path: "/page:num/"

# Sass settings (if applicable)
sass:
  style: compressed
